name: Convert Markdown into PDF
on: [push]

jobs:
  publish:
    runs-on: ubuntu-latest
    outputs:
        file_list: ${{ steps.generate_file_urls.outputs.file_list }}
    steps:
      - uses: actions/checkout@v4


      - name: Convert Markdown into PDF
        uses: KoharaKazuya/marp-cli-action@v2
        with:
          config-file: ./.marprc-ci.yml


      - name: Save outputs
        uses: actions/upload-artifact@v4
        with:
          name: marp_output
          path: ./output2


      - uses: actions/upload-pages-artifact@v1
        with:
          path: ./output2


      - name: Generate file URLs with CRLF
        id: generate_file_urls
        env:
          LINE_TOKEN: ${{ secrets.SECRET_LINE_NOTIFY_API_TOKEN }} # LINE NotifyのアクセストークンをGitHub Secretsから取得
        run: |
          # GitHub PagesのデプロイメントURLを環境変数から取得
          # PAGE_URL="${{ steps.deployment.outputs.page_url }}"


          # REPOSITORY_NAME = "${{github.repository}}"
          # REPOSITORY_NAME=${REPOSITORY_NAME#*/}

          # echo "$REPOSITORY_NAME"

          PAGE_URL="https://${{github.repository_owner}}.github.io${{github.repository}}/"

          FILES=$(find ./output2 -type f | sed 's|./output2/||g' | while read file; do echo "${PAGE_URL}${file// /%20} \n "; done | tr '\n' '%'  | sed 's/%/%%/g')
          FILES_WITH_URLS=$(echo "$FILES" | sed 's/%/\n/g')

          MESSAGE="Published Files URLs:\n$FILES_WITH_URLS"
          curl -X POST https://notify-api.line.me/api/notify \
          -H "Authorization: Bearer $LINE_TOKEN" \
          -F "message=$MESSAGE"




  deploy:
    needs: publish
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1




      - name: Generate file URLs with CRLF
        id: generate_file_urls2
        env:
          LINE_TOKEN: ${{ secrets.SECRET_LINE_NOTIFY_API_TOKEN }} # LINE NotifyのアクセストークンをGitHub Secretsから取得
        run: |
          # GitHub PagesのデプロイメントURLを環境変数から取得
          PAGE_URL="${{ steps.deployment.outputs.page_url }}"


          FILES = "${{ needs.publish.outputs.file_list }}""
          echo "$FILES"

          FILES_WITH_URLS=$(echo "$FILES" | sed 's/%/\n/g')

          MESSAGE="%20%20 $FILES_WITH_URLS"
          curl -X POST https://notify-api.line.me/api/notify \
          -H "Authorization: Bearer $LINE_TOKEN" \
          -F "message=$MESSAGE"
