name: Convert Markdown into PDF
on: [push]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Convert Markdown into PDF
        uses: KoharaKazuya/marp-cli-action@v2
        with:
          config-file: ./.marprc-ci.yml

      - name: Save outputs
        uses: actions/upload-artifact@v4
        with:
          name: marp_output
          path: ./output2

      - uses: actions/upload-pages-artifact@v1
        with:
          path: ./output2

  deploy:
    needs: publish
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1

      - uses: snow-actions/line-notify@v1.1.0
        with:
          access_token: ${{ secrets.SECRET_LINE_NOTIFY_API_TOKEN }}
          message: "Published File URL: ${{ steps.deployment.outputs.page_url }}"


      - name: Generate URLs of published files
        id: generate_urls
        run: |
          FILES=$(ls ./output2) # ここを修正しました
          URLS=""
          for FILE in $FILES; do
            URL="${{ steps.deployment.outputs.page_url }}/$FILE"
            URLS="$URLS\n$URL"
          done
          echo "::set-output name=urls::$URLS"


      - name: Notify published URLs via LINE
        uses: snow-actions/line-notify@v1.1.0
        with:
          access_token: ${{ secrets.SECRET_LINE_NOTIFY_API_TOKEN }}
          message: "Published Files URLs: ${{ steps.generate_urls.outputs.urls }}"
