name: Convert Markdown into PDF
on: [push]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Copy images from pub/*/images to output2
        run: |
          while IFS= read -r folder; do
            base_folder=$(basename $(dirname "$folder"))
            mkdir -p "output2/$base_folder/images"
            cp -r "$folder"/* "output2/$base_folder/images/"
          done < <(find pub -type d -name images)

      - name: Convert Markdown into PDF
        uses: KoharaKazuya/marp-cli-action@v2
        with:
          config-file: ./.marprc-ci.yml


      - name: Save outputs
        uses: actions/upload-artifact@v4
        with:
          name: marp_output
          path: ./output2


      - name: Generate file URLs with CRLF
        id: generate_file_urls
        env:
          LINE_TOKEN: ${{ secrets.SECRET_LINE_NOTIFY_API_TOKEN }} # LINE NotifyのアクセストークンをGitHub Secretsから取得
        run: |
          # GitHub PagesのデプロイメントURLを環境変数から取得
          # PAGE_URL="${{ steps.deployment.outputs.page_url }}"

          REPOSITORY_NAME=$(echo ${{ github.repository }} | cut -d'/' -f2)
          PAGE_URL="https://${{github.repository_owner}}.github.io/${REPOSITORY_NAME}/"
          FILES=$(find ./output2 \( -name "*.html" -or -name "*.pdf" \) -type f | sort | sed 's|./output2/||g' | while read file; do echo "<div class='docs_link'><a href=\"${PAGE_URL}${file// /%20}\">${file// /%20}</a></div> "; done)
          FILES_WITH_URLS=$(echo -e "<div>Commit message: 「${{ github.event.head_commit.message }}」</div>\n<div>$FILES</div>")


          MESSAGE=$(echo -e "◆以下のファイルがデプロイされました。\n Commit message: 「${{ github.event.head_commit.message }}」\n 下記URLからご確認下さい。 \n $PAGE_URL")
          curl -X POST https://notify-api.line.me/api/notify \
          -H "Authorization: Bearer $LINE_TOKEN" \
          -F "message=$MESSAGE"

          html_content="<html><body>$FILES_WITH_URLS</body></html>"
          echo "$html_content" > ./output2/index.html

      - uses: actions/upload-pages-artifact@v1
        with:
          path: ./output2


  deploy:
    needs: publish
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
